global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]
        labels:
          app: "prometheus"

  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "spring-mock:8086" ]
        labels:
          app: "spring-mock"

  - job_name: "node_exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]
        labels:
          app: "node-exporter"

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
        labels:
          app: "kafka-exporter"
